### ISSUE TITLE
Explore - Establish a metric for resource 'popularity' 

### ISSUE THREAD

**Issue by olwynlee** [concourse/dutyfree#65] opened 2019-07-14 15:26 UTC

**Comment by olwynlee** [comment] 2019-07-14 17:03
## Problem:
During user research users expressed a preference for having a multi-sort with the following options:
-Alphabetical (default ref [issue #66](https://github.com/concourse/dutyfree/issues/66
)
- Popularity
- Most Active

In order to implement sorting by 'popularity', it must first be determined what metrics to use as a measure of 'popularity', which is the purpose of this explore.

## Goal:
- The goal of this explore is to establish metric that quantifies a meaningful measure of 'popularity' based on what is possible and what is important to users. 

## Validation:
Below are some examples of quotes validating the user preference for multi-sort for resources with the options of alphabetical, popularity and most active.

"verified first and then popularity"
"would like to be able to sort based on popularity or relevance"
"Popularity, last time it was updated, Closed v open issues"
"Interested in popularity"
"trust: popularity, last updated, open/closed issues - ratio [maybe..?]"

## Thoughts and Questions:
An explore has already been opened to research possible popularity metrics prior to handing over to Concourse team; [issue #34 ](https://github.com/concourse/dutyfree/issues/65)

This explore could be approached as follows:

1. Identify what are the most important/meaningful measures of 'popularity'
2. Based on variables identified in step 1 above confirm what can be captured
3. Assign weights to variables that reflect degree of importance to user

At the moment there is no data being captured from the Duty Free website to measure popularity. 
In future iterations, the following could be considered as measures of popularity:

1. Number of times a resource is clicked on
2. Duty Free has a login and user profile that allows them to review and rate resources


## Screenshots/Link to prototype:
> Figma or screenshots implementation details like css etc. 


> Add a Label
> Put a label on it... " web-ui", "design-snack", "needs-triage" etc...

**Comment by ibagha** [comment] 2019-09-23 16:23
For v1, the only piece of data we have to work with to define popularity is the number of github stars a resource has. We will be using this as the metric for popularity. For v2, we might look at including docker/resource downloads as additional metrics for popularity.

**Comment by YoussB** [comment] 2019-11-26 18:26
closing as a duplicate of #132

**Closed by YoussB** 2019-11-26 18:26 UTC
Labels: sort, v2
